name: "Publish every Git push to master to FlakeHub"
on:
  push:
    branches:
      - "master"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4.3.1
      - uses: "DeterminateSystems/nix-installer-action@a7ad9c4f0c65208097f4d34f3cfa1913b80cce5c" # main
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@0e801cf490b3b3dcb099131a69146bc59d610d0f" # main
        with:
          name: "georgyo/avalon"
          rolling: true
          visibility: "public"
          include-output-paths: true
